"""
Market Anomaly Detector - Commit 6-S.0/6-S.1.

Finds Narrative Divergence: stocks where the market's pessimistic story
(price crashing, valuation compressing) contradicts the business reality
(earnings stable, cashflow improving, balance sheet healthy).

This is NOT a factor signal. Factors measure "is this stock cheap/quality?"
Anomaly detection measures "is the market WRONG about this stock?"

Key distinction from 6-Q thesis signals:
  - 6-Q signals: earnings_acceleration, mispricing_gap → IC was NEGATIVE
  - 6-S anomaly: market_pessimism VS business_strength → divergence object
  - 6-Q asked "will this stock go up?" → wrong question
  - 6-S asks "where is the market most likely wrong?" → right question

The MispricingObject is a structured investment thesis, not a score:
  - market_view: what the price implies
  - business_reality: what fundamentals show
  - divergence: the gap between the two
  - thesis: why the market is wrong (generated by doctrine)
  - invalidation: what would prove us wrong
  - confidence: how strong the divergence is

All data uses vintage-aware queries (6-R.0) to prevent look-ahead bias.

Usage:
    from src.thesis.market_anomaly import MarketAnomalyDetector
    detector = MarketAnomalyDetector()
    anomalies = detector.scan(trade_date="2022-04-01")
    # anomalies = [MispricingObject(...), ...]
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass

import numpy as np

from src.data.akshare_provider import AkshareProvider
from src.data.local_provider import LocalDataProvider
from src.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class V3CandidateFeatures:
    """6-S.13: v3 Candidate Generator extension fields.

    Advisory only - frozen modules (KillCriteria, DoctrineUnderwriter)
    never read these. Populated by CandidateGenerator (6-S.13.2+) and
    consumed by v3 replay for attribution.
    """

    recovery_score: float | None = None  # Stage 1 composite 0-100
    earnings_acceleration: float | None = None  # earnings_yoy_current - previous
    frm_direction: str | None = None  # improving/stable/deteriorating
    frm_score: float | None = None  # FRM score 0-100 (reuses 6-S.12.2)
    relative_strength: float | None = None  # Stage 2: stock_return - sector_return
    sector_strength: float | None = None  # Stage 2: sector_return - market_return
    rs_score: float | None = None  # Stage 2 composite 0-100
    liquidity_pass: bool | None = None  # Stage 1 liquidity gate
    candidate_stage: str | None = None  # stage1_pass/stage2_pass/stage3_pass/rejected
    rejection_reason: str | None = None  # LOW_LIQUIDITY/DETERIORATING/WEAK_RS/NO_MISPRICING


@dataclass
class MispricingObject:
    """A structured investment thesis about a market mispricing.

    Not a score. An OBJECT with a causal claim: "the market believes X,
    but reality is Y, therefore the price will correct."
    """

    code: str
    trade_date: str

    # Layer 1: Market Belief (what the price implies)
    price_drawdown_12m: float = 0.0  # -0.35 = -35% in 12 months
    pe_compression: float | None = 0.0  # PE_now / PE_1y_ago (0.4 = 60% compression)
    momentum_rank: float | None = 0.5  # 0 = bottom, 1 = top
    market_pessimism: float = 0.0  # composite 0-1 (1 = max pessimism)

    # Layer 2: Business Reality (what fundamentals show)
    roe: float = 0.0
    roe_stability: float | None = 0.0  # 1 = stable, 0 = volatile
    margin_change: float | None = 0.0  # Δ(gross_margin) positive = improving
    cashflow_trend: float | None = 0.0  # cashflow growth direction
    debt_ratio: float = 0.0  # debt_to_equity
    business_strength: float = 0.0  # composite 0-1 (1 = max strength)

    # Layer 3: Divergence
    divergence_score: float = 0.0  # business_strength - market_pessimism
    divergence_type: str = ""  # "market_overreaction" / "cyclical_misjudgment" / etc

    # Layer 4: Thesis (filled by doctrine, not here)
    thesis: str = ""  # "市场将周期性下滑误判为结构性恶化"
    invalidation: str = ""  # "margin cannot recover within 2 quarters"
    confidence: float = 0.0  # 0-1

    # Layer 5: v3 Candidate Generator features (6-S.13, advisory only)
    # Frozen modules (KillCriteria, DoctrineUnderwriter) never read these.
    v3_features: V3CandidateFeatures | None = None

    def is_anomaly(self, threshold: float = 0.15) -> bool:
        """Is this a significant narrative divergence?

        Threshold 0.15 (relaxed from 0.30) because the strict threshold
        found 0 anomalies in most dates. The divergence needs:
          - market_pessimism > 0.4 (some pessimism)
          - business_strength > 0.4 (some strength)
          - divergence_score > threshold (gap between the two)
        """
        return (
            self.divergence_score > threshold
            and self.market_pessimism > 0.4
            and self.business_strength > 0.4
        )

    def is_true_mispricing(self) -> bool:
        """Triage: is this a TRUE mispricing or a value trap?

        6-S.0.5 analysis of 2022-03 (failed) vs 2023-01 (succeeded)
        revealed three filters that separate real opportunities from traps:

        1. Price drawdown must be significant (< -15%, not just -5%)
           - Mild drawdowns aren't "market errors", just normal volatility
        2. ROE must be reasonable (0.02-0.50)
           - ROE > 0.50 is likely data error or one-off, inflates strength
        3. Margin change must be plausible (-0.5 to +0.5)
           - Extreme margin changes (>+1.0) are likely data noise
        4. Prefer cyclical_misjudgment type (price down + margin improving)
           - This is the strongest narrative divergence signal
        """
        # Filter 1: significant price drawdown
        if self.price_drawdown_12m > -0.15:
            return False

        # Filter 2: reasonable ROE (not data error)
        if self.roe > 0.50 or self.roe < 0.02:
            return False

        # Filter 3: plausible margin change
        if self.margin_change is not None and abs(self.margin_change) > 0.50:
            return False

        # Filter 4: must still pass basic anomaly check
        return self.is_anomaly()

    def triage_label(self) -> str:
        """Classify anomaly as opportunity, trap, or uncertain.

        Returns:
          - "true_mispricing": likely market error -> opportunity
          - "value_trap": likely structural deterioration -> avoid
          - "uncertain": not enough signal either way
        """
        # True mispricing: significant drawdown + reasonable fundamentals + improving
        if self.is_true_mispricing():
            if self.divergence_type == "cyclical_misjudgment":
                return "true_mispricing"  # strongest signal
            elif self.market_pessimism > 0.6 and self.business_strength > 0.6:
                return "true_mispricing"  # strong divergence
            else:
                return "uncertain"

        # Value trap: price falling but fundamentals also deteriorating
        if self.market_pessimism > 0.5 and self.business_strength < 0.5:
            return "value_trap"

        # Value trap: margin declining (business getting worse)
        if self.margin_change is not None and self.margin_change < -0.05:
            return "value_trap"

        return "uncertain"

    def to_dict(self) -> dict:
        return {
            "code": self.code,
            "trade_date": self.trade_date,
            "market_pessimism": round(self.market_pessimism, 3),
            "business_strength": round(self.business_strength, 3),
            "divergence_score": round(self.divergence_score, 3),
            "divergence_type": self.divergence_type,
            "price_drawdown_12m": round(self.price_drawdown_12m, 3),
            "roe": round(self.roe, 4),
            "margin_change": round(self.margin_change, 4)
            if self.margin_change is not None
            else None,
            "thesis": self.thesis,
            "confidence": round(self.confidence, 3),
        }


class MarketAnomalyDetector:
    """Detects Narrative Divergence: market pessimism vs business strength.

    Uses ONLY existing data (price history from TDX + financials from
    akshare with vintage-aware queries). No external data, no LLM.

    The detector finds candidates; the doctrine (6-S.1) generates the
    investment thesis and confidence.
    """

    def __init__(self, cache_db: str = "data/cache.db", eval_db: str = "data/evaluation.db"):
        self.cache_db = cache_db
        self.eval_db = eval_db
        self.local = LocalDataProvider()
        self.akshare = AkshareProvider(db_path=cache_db)

    def scan(
        self,
        trade_date: str,
        universe: list[str] | None = None,
        top_n: int = 50,
        triage: bool = True,
    ) -> list[MispricingObject]:
        """Scan the universe for narrative divergence anomalies.

        Args:
            trade_date: the date to scan (vintage-aware)
            universe: list of stock codes to scan. If None, uses all from
                      the latest stock_factor_snapshot.
            top_n: return top N anomalies by divergence_score
            triage: if True, only return "true_mispricing" (6-S.0.5).
                    If False, return all anomalies (including value traps).

        Returns: list of MispricingObject, sorted by divergence_score DESC
        """
        if universe is None:
            universe = self._get_universe(trade_date)

        anomalies = []
        for code in universe:
            try:
                obj = self._detect_anomaly(code, trade_date)
                if obj and obj.is_anomaly():
                    if triage:
                        if obj.triage_label() == "true_mispricing":
                            anomalies.append(obj)
                    else:
                        anomalies.append(obj)
            except Exception as e:
                logger.debug("anomaly_detector: %s failed: %s", code, e)

        # Sort by divergence_score
        anomalies.sort(key=lambda x: x.divergence_score, reverse=True)
        return anomalies[:top_n]

    def _detect_anomaly(self, code: str, trade_date: str) -> MispricingObject | None:
        """Detect narrative divergence for one stock.

        Computes:
          1. Market pessimism (price drawdown + PE compression + momentum rank)
          2. Business strength (ROE stability + margin change + cashflow + debt)
          3. Divergence = business_strength - market_pessimism
        """
        # Layer 1: Market Pessimism
        price_drawdown = self._compute_price_drawdown(code, trade_date, months=12)
        if price_drawdown is None:
            return None

        pe_compression = self._compute_pe_compression(code, trade_date)
        momentum_rank = self._compute_momentum_rank(code, trade_date)

        # Market pessimism composite (0-1, higher = more pessimistic)
        # Price drawdown is the primary signal
        pessimism_price = min(1.0, abs(min(0, price_drawdown)) / 0.5)  # -50% -> 1.0
        pessimism_pe = min(1.0, max(0, 1 - (pe_compression or 1.0))) if pe_compression else 0.5
        pessimism_momentum = 1.0 - (momentum_rank or 0.5)  # low momentum = pessimistic

        market_pessimism = 0.5 * pessimism_price + 0.3 * pessimism_momentum + 0.2 * pessimism_pe

        # Layer 2: Business Strength (vintage-aware)
        fin = self.akshare.get_financial_dict_vintage(code, trade_date)
        if not fin or not fin.get("roe"):
            return None

        roe = fin.get("roe", 0)
        debt_ratio = fin.get("debt_to_equity", 1.0)
        margin_change = self._compute_margin_change(code, trade_date)
        roe_stability = self._compute_roe_stability(code, trade_date)
        cashflow_trend = self._compute_cashflow_trend(code, trade_date)

        # Business strength composite (0-1, higher = stronger)
        strength_roe = min(1.0, max(0, roe / 0.20))  # ROE 20% -> 1.0
        stability = roe_stability or 0.5
        margin = max(0, min(1, 0.5 + (margin_change or 0) * 5))  # +10% margin -> 1.0
        cashflow = max(0, min(1, 0.5 + (cashflow_trend or 0) * 5))
        debt_health = max(
            0, min(1, 1.0 - (debt_ratio or 1.0) / 3.0)
        )  # debt/equity 0 -> 1.0, 3.0 -> 0

        business_strength = (
            0.30 * strength_roe
            + 0.20 * stability
            + 0.20 * margin
            + 0.15 * cashflow
            + 0.15 * debt_health
        )

        # Layer 3: Divergence
        divergence = business_strength - market_pessimism

        # Classify divergence type
        if market_pessimism > 0.7 and business_strength > 0.5:
            div_type = "market_overreaction"
        elif price_drawdown < -0.2 and margin_change and margin_change > 0:
            div_type = "cyclical_misjudgment"
        elif market_pessimism > 0.5 and roe > 0.10:
            div_type = "quality_oversold"
        else:
            div_type = "minor_divergence"

        # Confidence: based on data completeness + divergence magnitude
        confidence = min(1.0, max(0, divergence * 1.5))

        return MispricingObject(
            code=code,
            trade_date=trade_date,
            price_drawdown_12m=price_drawdown,
            pe_compression=pe_compression,
            momentum_rank=momentum_rank,
            market_pessimism=market_pessimism,
            roe=roe,
            roe_stability=roe_stability,
            margin_change=margin_change,
            cashflow_trend=cashflow_trend,
            debt_ratio=debt_ratio,
            business_strength=business_strength,
            divergence_score=divergence,
            divergence_type=div_type,
            confidence=confidence,
        )

    def _get_universe(self, trade_date: str) -> list[str]:
        """Get stock universe from snapshot."""
        conn = sqlite3.connect(self.eval_db)
        try:
            rows = conn.execute(
                "SELECT security_id FROM stock_factor_snapshot WHERE trade_date=?",
                (trade_date,),
            ).fetchall()
            return [r[0].split(".")[0] if "." in r[0] else r[0] for r in rows]
        finally:
            conn.close()

    def _compute_price_drawdown(self, code: str, trade_date: str, months: int = 12) -> float | None:
        """12-month price drawdown. Negative = price fell."""
        from datetime import date, timedelta

        start = (date.fromisoformat(trade_date) - timedelta(days=months * 30)).isoformat()

        try:
            kline = self.local.get_daily_kline(code, start, trade_date)
            if kline is None or kline.empty or len(kline) < 10:
                return None
            close = kline["close"].values
            return float((close[-1] - close[0]) / close[0])
        except Exception:
            return None

    def _compute_pe_compression(self, code: str, trade_date: str) -> float | None:
        """PE compression ratio: PE_now / PE_1y_ago. <1 = compressed."""
        from datetime import date, timedelta

        start = (date.fromisoformat(trade_date) - timedelta(days=365)).isoformat()

        fin_now = self.akshare.get_financial_dict_vintage(code, trade_date)
        fin_past = self.akshare.get_financial_dict_vintage(code, start)

        if not fin_now or not fin_past:
            return None

        pe_now = fin_now.get("pe_ttm")
        pe_past = fin_past.get("pe_ttm")

        if pe_now and pe_past and pe_past > 0:
            return pe_now / pe_past
        return None

    def _compute_momentum_rank(self, code: str, trade_date: str) -> float | None:
        """Momentum rank in universe (0=bottom, 1=top). From snapshot."""
        conn = sqlite3.connect(self.eval_db)
        try:
            row = conn.execute(
                "SELECT momentum_percentile FROM stock_factor_snapshot "
                "WHERE trade_date=? AND security_id=?",
                (trade_date, code),
            ).fetchone()
            if row and row[0] is not None:
                return row[0]
            # Fallback: use momentum_score / 100
            row = conn.execute(
                "SELECT momentum_score FROM stock_factor_snapshot "
                "WHERE trade_date=? AND security_id=?",
                (trade_date, code),
            ).fetchone()
            return (row[0] / 100.0) if row and row[0] else 0.5
        finally:
            conn.close()

    def _compute_margin_change(self, code: str, trade_date: str) -> float | None:
        """Change in net margin vs 4 quarters ago."""
        from datetime import date, timedelta

        start = (date.fromisoformat(trade_date) - timedelta(days=365)).isoformat()

        fin_now = self.akshare.get_financial_dict_vintage(code, trade_date)
        fin_past = self.akshare.get_financial_dict_vintage(code, start)

        if not fin_now or not fin_past:
            return None

        margin_now = fin_now.get("net_margin")
        margin_past = fin_past.get("net_margin")

        if margin_now is not None and margin_past is not None:
            return margin_now - margin_past
        return None

    def _compute_roe_stability(self, code: str, trade_date: str) -> float | None:
        """ROE stability: 1 - normalized_std of ROE across available periods."""
        conn = sqlite3.connect(self.cache_db)
        try:
            rows = conn.execute(
                "SELECT roe FROM akshare_financials WHERE code=? "
                "AND available_date IS NOT NULL AND available_date <= ? "
                "ORDER BY report_date DESC LIMIT 4",
                (code, trade_date),
            ).fetchall()
        finally:
            conn.close()

        if len(rows) < 3:
            return 0.5  # neutral

        roes = [r[0] for r in rows if r[0] is not None]
        if len(roes) < 3:
            return 0.5

        mean_roe = np.mean(roes)
        std_roe = np.std(roes)
        if abs(mean_roe) < 0.01:
            return 0.5

        cv = std_roe / abs(mean_roe)  # coefficient of variation
        return max(0, min(1, 1.0 - cv))  # low CV = high stability

    def _compute_cashflow_trend(self, code: str, trade_date: str) -> float | None:
        """Cashflow trend: net_profit growth direction (proxy for cashflow)."""
        from datetime import date, timedelta

        start = (date.fromisoformat(trade_date) - timedelta(days=365)).isoformat()

        fin_now = self.akshare.get_financial_dict_vintage(code, trade_date)
        fin_past = self.akshare.get_financial_dict_vintage(code, start)

        if not fin_now or not fin_past:
            return None

        np_now = fin_now.get("fcf")  # using net_profit as proxy (fcf field)
        np_past = fin_past.get("fcf")

        if np_now and np_past and np_past > 0:
            return (np_now - np_past) / abs(np_past)
        return None
